services:
  api:
    container_name: "compose-api"
    build:
      context: .
      dockerfile: Dockerfile.multi
    ports:
      - 8000:8080
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: postgres_db
      DB_PORT: 5432

  db:
    container_name: postgres_db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
